#!/usr/bin/env python

import click
from pwn import *
from pathlib import Path
import subprocess

file_format_string = """\"""
{file_output}
{checksec_output}
\"""

from pwn import *
from gloom_pwn.get_process import get_process

binary = "{binary}"
context.binary = ELF(binary)

p = get_process(
    binary=binary,
    debug=False
)

p.interactive()
"""

@click.command()
@click.argument('binary', type=click.Path(exists=True))
def analyse_binary(binary):

    e = ELF(binary)
    checksec_output = e.checksec(color=False)
    c = subprocess.run(["file", binary], text=True, capture_output=True)

    with open("exploit.py", "w") as f:
        py_file_content = file_format_string.format(
            file_output = c.stdout,
            checksec_output=checksec_output,
            binary=Path(binary).absolute().as_posix()
        )
        f.write(py_file_content)


    c = subprocess.run(["ropper", "--nocolor", "-f", binary], text=True, capture_output=True)

    with open("rop_gadgets", "w") as f:
        f.write(c.stdout)


if __name__ == "__main__":
    analyse_binary()
